apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/fueledbycoffee/qoffice-provisioner
    newTag: preprod-473046573ebb339d3fbbad50da01dc1d376c16d6
