apiVersion: v1
kind: PersistentVolumeClaim
metadata: { name: james-config-pvc, namespace: platform }
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: { name: james-logs-pvc, namespace: platform }
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 2Gi
