apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/fueledbycoffee/qoffice-preprod-gitops
    targetRevision: main
    path: root/apps/platform-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true