apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: qai-secrets
  namespace: platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: qai-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: QAI_POSTGRES_URL
      remoteRef:
        key: preprod/platform/database
        property: DATABASE_URL
