apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-conn
  namespace: platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: redis-conn
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
  data:
    - secretKey: url
      remoteRef:
        key: preprod/platform/redis
        property: url