apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-admin
  namespace: auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: keycloak-admin
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: KEYCLOAK_ADMIN
      remoteRef:
        key: preprod/infra/keycloak
        property: KEYCLOAK_ADMIN
    - secretKey: KEYCLOAK_ADMIN_PASSWORD
      remoteRef:
        key: preprod/infra/keycloak
        property: KEYCLOAK_ADMIN_PASSWORD
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-db
  namespace: auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: keycloak-db
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: KC_DB_USERNAME
      remoteRef:
        key: preprod/infra/keycloak
        property: KC_DB_USERNAME
    - secretKey: KC_DB_PASSWORD
      remoteRef:
        key: preprod/infra/keycloak
        property: KC_DB_PASSWORD
