apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-keycloak
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: keycloak
    targetRevision: 24.4.7
    helm:
      values: |
        auth:
          adminUser: admin
          existingSecret: keycloak-admin
          passwordSecretKey: admin-password
        postgresql:
          enabled: false
        externalDatabase:
          host: postgres-postgresql.infra.svc.cluster.local
          user: keycloak
          password: ""
          database: keycloak
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: auth
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [ CreateNamespace=true ]
