apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-keycloak
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/fueledbycoffee/qoffice-preprod-gitops
    targetRevision: main
    path: root/infra/keycloak
  destination:
    server: https://kubernetes.default.svc
    namespace: auth
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
