apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-minio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: minio
    targetRevision: 14.9.4
    helm:
      values: |
        auth:
          existingSecret: minio-secrets
          rootUserKey: root-user
          rootPasswordKey: root-password
        defaultBuckets: qoffice-preprod
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
        persistence:
          size: 50Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: data
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [ CreateNamespace=true ]
