apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: meilisearch-secret
  namespace: search
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: meilisearch-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
  data:
    - secretKey: MEILI_MASTER_KEY
      remoteRef:
        key: preprod/infra/meilisearch
        property: MEILI_MASTER_KEY