apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ops-vault
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.28.0
    helm:
      values: |
        global:
          tlsDisable: false

        server:
          ha:
            enabled: true
            raft:
              enabled: true
              setNodeId: true
          dataStorage:
            enabled: true
            storageClass: longhorn
            size: 10Gi
          auditStorage:
            enabled: true
            storageClass: longhorn
            size: 5Gi
          service:
            type: ClusterIP
            annotations:
              prometheus.io/scrape: "true"
              prometheus.io/port: "8200"
          ingress:
            enabled: true
            ingressClassName: traefik
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
              traefik.ingress.kubernetes.io/router.middlewares: kube-system-secure-headers@kubernetescrd
            hosts:
              - host: vault.preprod.qoffice.cloud
                paths:
                  - /
            tls:
              - hosts:
                  - vault.preprod.qoffice.cloud
                secretName: vault-tls
          authDelegator: true
          standalone:
            enabled: false
          extraEnvironmentVars:
            VAULT_LOG_LEVEL: info
          config: |
            ui = true

            listener "tcp" {
              address       = "0.0.0.0:8200"
              cluster_address = "0.0.0.0:8201"
              tls_disable = true
            }

            storage "raft" {
              path = "/vault/data"
            }

            api_addr     = "http://vault.vault.svc.cluster.local:8200"
            cluster_addr = "http://vault-0.vault-internal:8201"

        injector:
          enabled: false

        csi:
          enabled: false

        ui:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
