apiVersion: apps/v1
kind: Deployment
metadata:
  name: shell
  namespace: web
spec:
  replicas: 1
  selector: { matchLabels: { app: shell } }
  template:
    metadata: { labels: { app: shell } }
    spec:
      containers:
        - name: shell
          image: ghcr.io/fueledbycoffee/qoffice-shell:preprod-latest
          ports: [ { containerPort: 80 } ]
          volumeMounts:
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-run
              mountPath: /var/run
      volumes:
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-run
          emptyDir: {}
