apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault
spec:
  provider:
    vault:
      # Use HTTP for internal cluster communication (Vault listener has tls_disable = true)
      # External access via Ingress uses HTTPS with Let's Encrypt
      server: http://ops-vault.vault.svc.cluster.local:8200
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: auth/kubernetes
          role: external-secrets
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets