apiVersion: apps/v1
kind: Deployment
metadata: { name: billing, namespace: platform }
spec:
  replicas: 1
  selector: { matchLabels: { app: billing } }
  template:
    metadata: { labels: { app: billing } }
    spec:
      containers:
        - name: billing
          image: ghcr.io/fueledbycoffee/qoffice-billing:preprod-latest
          ports: [ { containerPort: 8080 } ]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: billing-secrets
                  key: DATABASE_URL
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: billing-secrets
                  key: STRIPE_SECRET_KEY
            - name: STRIPE_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: billing-secrets
                  key: STRIPE_WEBHOOK_SECRET
